from PIL import Image,ImageFilter as iff,ImageEnhance as ie,ImageTk
import tkinter as tk
from math import factorial,pi,asin,acos,atan,sin,cos,tan,log,e
from sympy.abc import x
from sympy import solve,diff, integrate,Matrix,det
import numpy as np
from deep_translator import GoogleTranslator as tro
from langdetect import detect,lang_detect_exception,DetectorFactory as d,detect_langs as de
window=tk.Tk()
window.geometry("1000x1000")
cf=tk.Frame(window)
cf.pack(fill="both", expand=True)
c=tk.Canvas(cf)
c.pack(side="left",fill="both",expand=True)
c.config(width=650)
sb=tk.Scrollbar(cf)
sb1=tk.Scrollbar(cf)
sb.pack(side="right",fill="y",expand=False)
sb1.pack(side="top",fill="x",expand=False)
c.configure(yscrollcommand=sb.set)
c.configure(xscrollcommand=sb1.set)
sb.configure(command=c.yview)
sb1.configure(command=c.xview)
sf=tk.Frame(c)
fos=("Arial",9)
fob=("Arial",11)
c.create_window((0,0), window=sf,anchor="nw")
cf.propagate(True)
sf.configure(background="white")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg as f
fig=plt.Figure(figsize=((3.2,6.4)),dpi=170)
plo=fig.add_subplot(111)
tk.Label(sf,text="SUPER COMPUTER 2.O\n Made by:- ADITYA\n",font=fob,fg="black",bg="white").grid(column=0,row=0)
tk.Label(sf,text="MENU:-",font=fob,bg="white").grid(column=0,row=1)
tk.Label(sf,text="Click on your choice:",font=("Arial",10),bg="white").grid(column=0,row=2)
def o66(k):
        for w in sf.grid_slaves(row=k, column=1):
          w.destroy() 
def add():
   o66(4)
   o66(5)
   tk.Label(sf,text="Number 1",font=fos,bg="white").grid(row=4, column=0)
   a=tk.Entry(sf,width=10)
   a.grid(column=1,row=4)
   tk.Label(sf,text="Number 2",font=fos,bg="white").grid(column=0,row=5)
   b=tk.Entry(sf,width=10)
   b.grid(column=1,row=5)
   def aclick():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=7)
    tk.Label(sf,text=x+y,font=fos,bg="white").grid(column=0,row=8)
   bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(row=6, column=0)
def sub():
  o66(10)
  o66(11)
  tk.Label(sf,text="Number 1",font=fos,bg="white").grid(column=0,row=10)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=10)
  tk.Label(sf,text="Number 2",font=fos,bg="white").grid(column=0,row=11)
  b=tk.Entry(sf,width=10)
  b.grid(column=1,row=11)
  def aclick():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=13)
    tk.Label(sf,text=x-y,font=fos,bg="white").grid(column=0,row=14)
    
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=12)
def mul():
  o66(16)
  o66(17)
  tk.Label(sf,text="Number 1",font=fos,bg="white").grid(column=0,row=16)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=16)
  tk.Label(sf,text="Number 2",font=fos,bg="white").grid(column=0,row=17)
  b=tk.Entry(sf,width=10)
  b.grid(column=1,row=17)
  def aclick():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=19)
    tk.Label(sf,text=x*y,font=fos,bg="white").grid(column=0,row=20)
    
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=18)
def div():
  o66(22)
  o66(23)
  tk.Label(sf,text="Number 1",font=fos,bg="white").grid(column=0,row=22)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=22)
  tk.Label(sf,text="Number 2",font=fos,bg="white").grid(column=0,row=23)
  b=tk.Entry(sf,width=10)
  b.grid(column=1,row=23)
  def aclick():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=25)
    tk.Label(sf,text=x/y,font=fos,bg="white").grid(column=0,row=26)
    
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=24)
def sqr():
  o66(28)
  tk.Label(sf,text="Number 1",font=fos,bg="white").grid(column=0,row=28)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=28)
  def aclick():
    x=eval(a.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=30)
    tk.Label(sf,text=x**(0.5),font=fos,bg="white", wraplength=400).grid(column=0,row=31)
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=29)
def fact():
  o66(33)
  tk.Label(sf,text="Number 1",font=fos,bg="white").grid(column=0,row=33)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=33)
  def aclick():
    x=int(a.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=35)
    tk.Label(sf,text=factorial(x),font=fos,bg="white", wraplengt=400).grid(column=0,row=36)
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=34)
def pow():
  o66(38)
  o66(39)
  tk.Label(sf,text="Base",font=fos,bg="white").grid(column=0,row=38)
  a=tk.Entry(sf,width=10)
  a.grid(column=1,row=38)
  tk.Label(sf,text="Power",font=fos,bg="white").grid(column=0,row=39)
  b=tk.Entry(sf,width=10)
  b.grid(column=1,row=39)
  def aclick():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result:-",font=fos,bg="white").grid(column=0,row=41)
    tk.Label(sf,text=x**y,font=fos,bg="white", wraplength=400).grid(column=0,row=42)
  bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=40)
def trig():
  def Sin():
    o66(45)
    l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=45)
    a=tk.Entry(sf,width=10)
    a.grid(column=1,row=45)
    def aclick():
      x=eval(a.get())
      tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=47,column=0)
      tk.Label(sf,text=round(sin(x),2),font=fos,bg="white").grid(row=48, column=0)
    bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=46)
  def Cos():
      o66(50)
      l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=50)
      a=tk.Entry(sf,width=10)
      a.grid(column=1,row=50)
      def aclick():
        x=eval(a.get())
        tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=52,column=0)
        tk.Label(sf,text=round(cos(x),2),font=fos,bg="white").grid(row=53, column=0)
      bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=51)
  def Tan():
    o66(55)
    l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=55)
    a=tk.Entry(sf,width=10)
    a.grid(column=1,row=55)
    def aclick():
        x=eval(a.get())
        tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=57,column=0)
        tk.Label(sf,text=round(tan(x),2),font=fos,bg="white").grid(row=58,column=0)
    bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=56)
  def Cosec():
       o66(60)
       l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=60)
       a=tk.Entry(sf,width=10)
       a.grid(column=1,row=60)
       def aclick():
        x=eval(a.get())
        tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=62,column=0)
        tk.Label(sf,text=round(1/sin(x),2),font=fos,bg="white").grid(row=63, column=0)
       bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=61)
  def Sec():
           o66(65)
           l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=65)
           a=tk.Entry(sf,width=10)
           a.grid(column=1,row=65)
           def aclick():
             x=eval(a.get())
             tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=67,column=0)
             tk.Label(sf,text=round(1/cos(x),2),font=fos,bg="white").grid(row=68, column=0)
           bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=66)
  def Cot():
    o66(70)     
    l1=tk.Label(sf,text="Angle",font=fos,bg="white").grid(column=0,row=70)
    a=tk.Entry(sf,width=10)
    a.grid(column=1,row=70)
    def aclick():
        x=eval(a.get())
        tk.Label(sf,text="Result :-",font=fos,bg="white").grid(row=72,column=0)
        tk.Label(sf,text=round(1/tan(x),2),font=fos,bg="white").grid(row=73, column=0)
    bt=tk.Button(sf,text="Enter", command=aclick,bg="white").grid(column=0,row=71)           
  bt8_1=tk.Button(sf,text="Sin",command=Sin,bg="black",fg="white").grid(column=0,row=44)
  bt8_2=tk.Button(sf,text="Cos",command=Cos,bg="black",fg="white").grid(column=0,row=49)
  bt8_3=tk.Button(sf,text="Tan",command=Tan,bg="black",fg="white").grid(column=0,row=54)
  bt8_3=tk.Button(sf,text="Cosec",command=Cosec,bg="black",fg="white").grid(column=0,row=59)
  bt8_3=tk.Button(sf,text="Sec",command=Sec,bg="black",fg="white").grid(column=0,row=64)
  bt8_4=bt8_3=tk.Button(sf,text="Cot",command=Cot,bg="black",fg="white").grid(column=0,row=69)
def area():
  def square():
    o66(77)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=79, column=0)
      tk.Label(sf,text=x*x,font=fos,bg="white").grid(row=80, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=80, column=1)
    tk.Label(sf,text="Side",font=fos,bg="white").grid(row=77, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=77, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=78, column=0)
  def rectangle():
    o66(82)
    o66(83)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=85, column=0)
      tk.Label(sf,text=x*y,font=fos,bg="white").grid(row=86, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=86, column=1)
      
    tk.Label(sf,text="Length",font=fos,bg="white").grid(row=82, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=82, column=1)
    tk.Label(sf,text="Breadth",font=fos,bg="white").grid(row=83, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=83, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=84, column=0)
  def circle():
         o66(88)
         def calc():
           r=eval(a.get())
           tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=90, column=0)
           tk.Label(sf,text=pi*r*r,font=fos,bg="white").grid(row=91, column=0)
           tk.Label(sf,text="unit²",font=fos,bg="white").grid(column=1,row=91)
         tk.Label(sf,text="Radius",font=fos,bg="white").grid(row=88, column=0)
         a=tk.Entry(sf,width=10)
         a.grid(row=88, column=1)
         tk.Button(sf,text="Enter",bg="white", command=calc,font=fos).grid(row=89, column=0)
  def parallel():
    o66(93)
    o66(94)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=96, column=0)
      tk.Label(sf,text=x*y,font=fos,bg="white").grid(row=97, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=97, column=1)
         
    tk.Label(sf,text="Height",font=fos,bg="white").grid(row=93, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=93, column=1)
    tk.Label(sf,text="Base",font=fos,bg="white").grid(row=94, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=94, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=95, column=0)  
  def rhomb():
    o66(99)
    o66(100)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=102,column=0)
      tk.Label(sf,text=0.5*x*y,font=fos,bg="white").grid(row=103, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=103, column=1)            
    tk.Label(sf,text="Diagonal 1",font=fos,bg="white").grid(row=99, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=99, column=1)
    tk.Label(sf,text="Diagonal 2",font=fos,bg="white").grid(row=100, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=100, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=101,column=0)                             
  def tri():
    o66(105)
    o66(106)
    o66(107)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      z=eval(f.get())
      r=(x+y+z)*0.5
      ar=(r*(r-x)*(r-y)*(r-z))**0.5
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=109, column=0)
      tk.Label(sf,text=round(ar,2),font=fos,bg="white").grid(row=110, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=110, column=1)
    tk.Label(sf,text="Side 1",font=fos,bg="white").grid(row=105, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=105, column=1)
    tk.Label(sf,text="Side 2",font=fos,bg="white").grid(row=106,column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=106,column=1)
    tk.Label(sf,text="Side 3",font=fos,bg="white").grid(row=107, column=0)
    f=tk.Entry(sf, width=10)
    f.grid(row=107, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=108, column=0)               
  def ellip():
    o66(112)
    o66(113)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=115, column=0)
      tk.Label(sf,text=fround(pi*x*y*0.25,2),font=fos,bg="white").grid(row=116, column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=116, column=1)
      
    tk.Button(sf,text="Major axis",font=fos,bg="white").grid(row=112, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=112, column=1)
    tk.Button(sf,text="Minor axis",font=fos,bg="white").grid(row=113,column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=113,column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=114, column=0)                 
  def trap():
    o66(119)
    o66(120)
    o66(121)
    def calc():
      x=eval(a.get())
      y=eval(b.get())
      z=eval(f.get())
      r=(x+y+z)*0.5
      ar=(0.5*(x+y)*z)
      tk.Label(sf,text="Area is",font=fos,bg="white").grid(row=123, column=0)
      tk.Label(sf,text=round(ar,2),font=fos,bg="white").grid(row=124,column=0)
      tk.Label(sf,text="unit²",font=fos,bg="white").grid(row=124,column=1)
      
    tk.Label(sf,text="Parallel side 1",font=fos,bg="white").grid(row=119, column=0)
    a=tk.Entry(sf,width=10)
    a.grid(row=119, column=1)
    tk.Label(sf,text="Parallel side 2",font=fos,bg="white").grid(row=120,column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=120,column=1)
    tk.Label(sf,text="Height",font=fos,bg="white").grid(row=121, column=0)
    f=tk.Entry(sf, width=10)
    f.grid(row=121, column=1)
    tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=122, column=0)          
    
    
  tk.Button(sf,text="Square", command=square,bg="black",fg="white").grid(row=76, column=0)
  tk.Button(sf,text="Rectangle", command=rectangle,bg="black",fg="white").grid(row=81, column=0)   
  tk.Button(sf,text="Circle", command=circle,bg="black",fg="white").grid(row=87, column=0)
  tk.Button(sf,text="Parallelogram", command=parallel,bg="black",fg="white").grid(row=92, column=0)
  tk.Button(sf,text="Rhombus", command=rhomb,bg="black",fg="white").grid(row=98, column=0)
  tk.Button(sf,text="Triangle", command=tri,bg="black",fg="white").grid(row=104, column=0)
  tk.Button(sf,text="Ellipse", command=ellip,bg="black",fg="white").grid(row=111, column=0)
  tk.Button(sf,text="Trapezium", command=trap,fg="white",bg="black").grid(row=118, column=0)
def itrig():
  def icot():
    o66(152)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=154, column=0)
      tk.Label(sf,text=round(atan(1/x),3),font=fos,bg="white").grid(row=155, column=0)
      
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=152, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=152, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=153, column=0)
  def isec():
    o66(147)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=149, column=0)
      tk.Label(sf,text=round(acos(1/x),3),font=fos,bg="white").grid(row=150, column=0)
      
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=147, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=147, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=148, column=0)
  def icosec():
    o66(142)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=144, column=0)
      tk.Label(sf,text=round(asin(1/x),3),font=fos,bg="white").grid(row=145, column=0)
      
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=142, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=142, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=143, column=0)
  def itan():
    o66(137)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=139,column=0)
      tk.Label(sf,text=round(atan(x),3),font=fos,bg="white").grid(row=140, column=0)
      
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=137, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=137, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=138, column=0)
    
  def icos():
    o66(132)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=134, column=0)
      tk.Label(sf,text=round(acos(x),3),font=fos,bg="white").grid(row=135, column=0)
      
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=132, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=132, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=133, column=0)
    
  def isin():
    o66(127)
    def calc():
      x=eval(a.get())
      tk.Label(sf,text="Angle is",bg="white",font=fos).grid(row=129, column=0)
      tk.Label(sf,text=round(asin(x),2),font=fos,bg="white").grid(row=130, column=0)
    tk.Label(sf,text="Value",bg="white",font=fos).grid(row=127, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=127, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=128)
  tk.Button(sf,text="Sin inverse",font=fos,bg="black",fg="white", command=isin).grid(row=126, column=0)
  tk.Button(sf,text="Cos inverse",font=fos,bg="black",fg="white", command=icos).grid(row=131, column=0)
  tk.Button(sf,text="Tan inverse",font=fos,bg="black",fg="white", command=itan).grid(row=136, column=0)
  tk.Button(sf,text="Cosec inverse",font=fos,bg="black",fg="white", command=icosec).grid(row=141, column=0)
  tk.Button(sf,text="Sec inverse",font=fos,bg="black",fg="white", command=isec).grid(row=146, column=0)
  tk.Button(sf,text="Cot inverse",font=fos,bg="black",fg="white", command=icot).grid(row=151, column=0)
def Log():
  o66(157)
  o66(158)
  def calc():
    x=eval(a.get())
    y=eval(b.get())
    tk.Label(sf,text="Result is",font=fos,bg="white").grid(row=160, column=0)
    tk.Label(sf,text=round(log(x,y),3),font=fos,bg="white").grid(row=161, column=0)
  tk.Label(sf,text="Number",font=fos,bg="white").grid(row=157, column=0)
  a=tk.Entry(sf,width=10)
  a.grid(row=157, column=1)
  tk.Label(sf,text="Base",font=fos,bg="white").grid(row=158, column=0)
  b=tk.Entry(sf, width=10)
  b.grid(row=158, column=1)
  tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=159, column=0)
def ln():
  o66(163)
  def calc():
    x=eval(a.get())
    tk.Label(sf,text="Result is",bg="white",font=fos).grid(row=164, column=0)
    tk.Label(sf,text=round(log(x),2),bg="white",font=fos).grid(row=165, column=0)
  tk.Label(sf,text="Number",bg="white",font=fos).grid(row=163, column=0)
  a=tk.Entry(sf, width=10)
  a.grid(row=163, column=1)
  tk.Button(sf,text="Enter",bg="white", command=calc,font=fos).grid(row=164, column=0)
def calculus():
  def inte():
    def woli():
      r=str(da.get("1.0",tk.END))
      tk.Label(sf,text="Result is",font=fos,bg="white").grid(row=182, column=0)
      tk.Label(sf,text=integrate(r,x),font=fos,bg="white", wraplength=400).grid(row=183, column=0)
    def wli():
      o66(176)
      o66(177)
      def calc():
        p=eval(u.get())
        q=eval(l.get())
        r=str(da.get("1.0",tk.END))
        tk.Label(sf,text="Result is",font=fos,bg="white").grid(row=179, column=0)
        tk.Label(sf,text=integrate(r,(x,q,p)),font=fos,bg="white", wraplength=400).grid(row=180, column=0)
      tk.Label(sf,text="Upper limit",font=fos,bg="white").grid(row=176, column=0)
      u=tk.Entry(sf, width=10)
      u.grid(row=176, column=1)
      tk.Label(sf,text="Lower limit",font=fos,bg="white").grid(row=177, column=0)
      l=tk.Entry(sf, width=10)
      l.grid(row=177, column=1)
      tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=178, column=0)
    tk.Label(sf,text="Equation",bg="white",font=fos).grid(row=174, column=0)
    da=tk.Text(sf, width=10,wrap=tk.WORD, height=6)
    da.grid(row=174, column=1)
    tk.Button(sf,text="With limits",font=fos,bg="red",fg="black", command=wli).grid(row=175, column=0)
    tk.Button(sf,text="Without limits",font=fos,bg="red",fg="black", command=woli).grid(row=181, column=0)
    
  def Diff():
    o66(168)
    o66(169)
    def calc():
      m=str(a.get("1.0",tk.END))
      y=int(b.get())
      tk.Label(sf,text="Result is",font=fos,bg="white").grid(row=171, column=0)
      tk.Label(sf,text=diff(m,x,y),font=fos,bg="white", wraplength=400).grid(row=172, column=0)
    tk.Label(sf,text="Equation",font=fos,bg="white").grid(row=168, column=0)
    a=tk.Text(sf, width=10, height=6,wrap=tk.WORD)
    a.grid(row=168, column=1)
    tk.Label(sf,text="Order",font=fos,bg="white").grid(row=169, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=169, column=1)
    tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=170, column=0)
  tk.Button(sf,text="Differentiation",font=fos,bg="black",fg="white", command=Diff).grid(row=167, column=0)
  tk.Button(sf,text="Integration",font=fos,bg="black",fg="white", command=inte).grid(row=173, column=0)
def mat():
  def matrrec():
    o66(247)
    o66(248)
    o66(249)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=251,column=0)
      tk.Label(sf,text=m1.rref(),font=fos,bg="white", wraplength=400).grid(row=252,column=0) 
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=247, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=247,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=248, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=248,column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=249,column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=249,column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=250, column=0)
    
  def matrec():
    o66(240)
    o66(241)
    o66(242)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=244,column=0)
      tk.Label(sf,text=m1.echelon_form(),font=fos,bg="white", wraplength=400).grid(row=245,column=0) 
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=240, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=240,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=241, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=241, column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=242,column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=242,column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=243, column=0)
    
  def matadj():
    o66(233)
    o66(234)
    o66(235)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="Adjoint(Matrix)",font=fos,bg="white").grid(row=237,column=0)
      tk.Label(sf,text=m1.adjugate(),font=fos,bg="white", wraplength=400).grid(row=238,column=0) 
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=233, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=233,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=234, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=234, column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=235,column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=235,column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=236, column=0)
    
  def matd():
    o66(226)
    o66(227)
    o66(228)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="|Matrix|",font=fos,bg="white").grid(row=230,column=0)
      tk.Label(sf,text=det(m1),font=fos,bg="white", wraplength=400).grid(row=231, column=0)
      
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=226, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=226,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=227, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=227, column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=228,column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=228,column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=229, column=0)
  def matp():
    o66(218)
    o66(219)
    o66(220)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      x=int(d.get())
      tk.Label(sf,text=f"Matrix^{x}",font=fos,bg="white").grid(row=223,column=0)
      tk.Label(sf,text=(m1**(x)),font=fos,bg="white", wraplength=400).grid(row=224, column=0)
      
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=218, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=218,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=219, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=219, column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=220, column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=220,column=1)
    tk.Label(sf,text="Exponent",bg="white",font=fos).grid(row=221, column=0)
    d=tk.Entry(sf,width=10)
    d.grid(row=221, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=222, column=0)
    
  def mati():
    o66(211)
    o66(212)
    o66(213)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="1/Matrix",font=fos,bg="white").grid(row=215,column=0)
      tk.Label(sf,text=(m1**(-1)),font=fos,bg="white", wraplength=400).grid(row=216, column=0)
      
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=211, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=211,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=212, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=212, column=1)
    tk.Label(sf,text="Matrix",font=fos,bg="white").grid(row=213, column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=213, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=214, column=0)
    
  def mmult():
    o66(200)
    o66(201)
    o66(202)
    o66(204)
    o66(205)
    o66(206)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      m2=Matrix(np.array(eval(c1.get("1.0",tk.END))). reshape((int(a1.get()),int(b1.get()))))
      tk.Label(sf,text="Matrix 1×Matrix 2",font=fos,bg="white").grid(row=208, column=0)
      tk.Label(sf,text=(m1*m2),font=fos,bg="white", wraplength=400).grid(row=209, column=0)
      
    tk.Label(sf,text="For Matrix 1-:",font=fos,bg="white").grid(row=199, column=0)
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=200, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=200,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=201,column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=201,column=1)
    tk.Label(sf,text="Matrix 1",font=fos,bg="white").grid(row=202, column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=202, column=1)
    tk.Label(sf,text="For Matrix 2",font=fos,bg="white").grid(row=203, column=0)
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=204, column=0)
    a1=tk.Entry(sf,width=10)
    a1.grid(row=204,column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=205,column=0)
    b1=tk.Entry(sf, width=10)
    b1.grid(row=205, column=1)
    tk.Label(sf,text="Matrix 2",font=fos,bg="white").grid(row=206,column=0)
    c1=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c1.grid(row=206, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=207, column=0)
  def msub():
    o66(191)
    o66(192)
    o66(193)
    o66(194)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      m2=Matrix(np.array(eval(d.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="Matrix 1-Matrix 2",font=fos,bg="white").grid(row=196,column=0)
      tk.Label(sf,text=(m1-m2),font=fos,bg="white", wraplength=400).grid(row=197, column=0)
      
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=191, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=191, column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=192, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=192, column=1)
    tk.Label(sf,text="Matrix 1",font=fos,bg="white").grid(row=193, column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=193, column=1)
    tk.Label(sf,text="Matrix 2",font=fos,bg="white").grid(row=194,column=0)
    d=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    d.grid(row=194, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=195, column=0)
  def madd():
    o66(183)
    o66(184)
    o66(185)
    o66(186)
    def calc():
      m1=Matrix(np.array(eval(c.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      m2=Matrix(np.array(eval(d.get("1.0",tk.END))).reshape((int(a.get()),int(b.get()))))
      tk.Label(sf,text="Matrix 1+Matrix 2",font=fos,bg="white").grid(row=188,column=0)
      tk.Label(sf,text=(m1+m2),font=fos,bg="white", wraplength=400).grid(row=189, column=0)
      
    tk.Label(sf,text="No. of rows",font=fos,bg="white").grid(row=183, column=0)
    a=tk.Entry(sf, width=10)
    a.grid(row=183, column=1)
    tk.Label(sf,text="No. of columns",font=fos,bg="white").grid(row=184, column=0)
    b=tk.Entry(sf, width=10)
    b.grid(row=184, column=1)
    tk.Label(sf,text="Matrix 1",font=fos,bg="white").grid(row=185, column=0)
    c=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    c.grid(row=185, column=1)
    tk.Label(sf,text="Matrix 2",font=fos,bg="white").grid(row=186, column=0)
    d=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
    d.grid(row=186, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=calc).grid(row=187, column=0)
  tk.Button(sf,text="Add",bg="black",fg="white", command=madd).grid(row=182, column=0)
  tk.Button(sf,text="Subtract",bg="black",fg="white", command=msub).grid(row=190, column=0)
  tk.Button(sf,text="Multiply",bg="black",fg="white", command=mmult).grid(row=198, column=0)
  tk.Button(sf,text="Inverse",fg="white",bg="black", command=mati).grid(row=210, column=0)
  tk.Button(sf,text="Power",fg="white",bg="black", command=matp).grid(row=217, column=0)
  tk.Button(sf,text="Determinant",fg="white",bg="black", command=matd).grid(row=225, column=0)
  tk.Button(sf,text="Adjoint",fg="white",bg="black", command=matadj).grid(row=232, column=0)
  tk.Button(sf,text="Row Echelon Form",bg="black",fg="white", command=matrec).grid(row=239, column=0)
  tk.Button(sf,text="Row Reduced Echelon Form",fg="white",bg="black", command=matrrec).grid(row=246, column=0)
def eq():
  o66(248)
  def calc():
    m=solve(eval(a.get("1.0",tk.END)))
    tk.Label(sf,text="Roots are",font=fos,bg="white").grid(row=250, column=0)
    tk.Label(sf,text=m,font=fos,bg="white", wraplength=400).grid(row=251, column=0)
  tk.Label(sf,text="Equation",bg="white",font=fos).grid(row=248, column=0)
  a=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
  a.grid(row=248, column=1)
  tk.Button(sf,text="Enter",bg="white", command=calc).grid(row=249,column=0)
def langt():
  o66(253)
  def calc():
    for op in sf.grid_slaves(row=256, column=0):
      op.destroy()
    x=a.get("1.0",tk.END)
    tk.Label(sf,text="Translation",font=fos,bg="white").grid(row=255, column=0)
    trans=tro(source="auto",target="en")
    dest=tk.Label(sf,text=trans.translate(x),font=fos,bg="white", wraplength=350).grid(row=256, column=0)
  tk.Label(sf,text="Sentence",font=fos,bg="white").grid(row=253, column=0)
  a=tk.Text(sf,width=10, height=5,wrap=tk.WORD)
  a.grid(row=253, column=1)
  tk.Button(sf,text="Enter",bg="white",font=fos,command=calc).grid(row=254, column=0)
def graphe():
  o66(258)
  o66(259)
  o66(260)
  def clean():
    plo.clear()
    plo.plot(0,0)
    c=f(fig,master=sf)
    c.draw()
    c.get_tk_widget().grid(row=262,column=0)
  def calc():
    
    from numpy import sin,cos,tan,log,pi,e
    xu=eval((b.get()))
    xl=eval((b1.get()))
    x=np.arange(xl,xu,0.00001)
    y=eval((a.get()))
    plo.set_xlabel="x"
    plo.set_ylabel="f(x)"
    plo.plot(x,y)
    plo.set_ylim(-5,5)
    c=f(fig,master=sf)
    c.draw()
    c.get_tk_widget().grid(row=262,column=0)
    
  tk.Label(sf,text="f(x)",font=fos,bg="white").grid(row=258, column=0)
  a=tk.Entry(sf, width=10)
  a.grid(row=258, column=1)
  tk.Label(sf,text="Upper x",font=fos,bg="white").grid(row=259, column=0)
  b=tk.Entry(sf, width=10)
  b.grid(row=259, column=1)
  tk.Label(sf,text="Lower x",font=fos,bg="white").grid(row=260, column=0)
  b1=tk.Entry(sf, width=10)
  b1.grid(row=260,column=1)
  tk.Button(sf,text="Enter", command=calc,font=fos,bg="white").grid(row=261, column=0)
  tk.Button(sf,text="Clear", command=clean,bg="white").grid(row=262, column=1)
def phoed():
  def modf():
    def pclear():
      pol=Image.new("RGB",(550,550),(255,255,255))
      plo=ImageTk.PhotoImage(pol)
      phdisp=tk.Label(sf,image=plo)
      phdisp.image=plo
      phdisp.grid(row=320, column=0)
    def psve():
      def calc():
        nume=str(x.get("1.0",tk.END))
        form=str(y.get())
        pname=(nume).strip()+"."+(form).strip()
        imge.save(pname)
        tk.Label(sf,text="Image is saved.",font=fos,bg="yellow").grid(row=308, column=0)
      tk.Label(sf,text="Name",font=fos,bg="white").grid(row=304, column=0)
      x=tk.Text(sf, width=10,height=5)
      x.grid(row=305, column=0)
      tk.Label(sf,text="Format",font=fos,bg="white").grid(row=306, column=0)
      y=tk.Entry(sf, width=10)
      y.grid(row=306, column=1)
      tk.Button(sf,text="Enter",bg="white",font=fos, command=calc).grid(row=307, column=0)
    def pres():
      global imge
      global img
       
      imge=img.copy()
      imge.thumbnail((550,550))
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=320,column=0)
    def phe():
      pclear()
      global imge
      imge=imge.filter(iff.CONTOUR)
      imge.thumbnail((550,550))
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=320, column=0)
    def pde():
      pclear()
      global imge
      imge=imge.filter(iff.FIND_EDGES)
      imge.thumbnail((550,550))
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=320, column=0)
    def p3d():
      pclear() 
      global imge
      imge=imge.filter(iff.EMBOSS)
      imge.thumbnail((550,550))
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=320, column=0)
    def rop():
      o66(294)
      def acrpcalc():
        pclear()
        global imge
        ang=eval(a.get())
        imge=imge.rotate(ang)
        imge.thumbnail((550,550))
        photo=ImageTk.PhotoImage(imge)
        phdisp=tk.Label(sf,image=photo)
        phdisp.image=photo
        phdisp.grid(row=320, column=0)
      def crpcalc():
        pclear()
        global imge
        ang=eval(a.get())
        imge=imge.rotate(ang,expand=False)
        imge.thumbnail((550,550))
        photo=ImageTk.PhotoImage(imge)
        phdisp=tk.Label(sf,image=photo)
        phdisp.image=photo
        phdisp.grid(row=320, column=0)
      tk.Label(sf,text="Angle",font=fos,bg="white").grid(row=294, column=0)
      a=tk.Entry(sf,width=10)
      a.grid(row=294, column=1)
      tk.Button(sf,text="Clockwise",font=fos,bg="Green", command=crpcalc).grid(row=295, column=0)
      tk.Button(sf,text="Anticlockwise",font=fos,bg="green", command=acrpcalc).grid(row=296, column=0)
    def rsp():
      o66(290)
      o66(291)
      def ccalc():
        pclear()
        global img,imge
        wdth=eval(a.get())
        heigh=eval(b.get())
        imge=imge.resize((wdth,heigh))
        imge.thumbnail((550,550))
        photo=ImageTk.PhotoImage(imge)
        phdisp=tk.Label(sf,image=photo)
        phdisp.image=photo
        phdisp.grid(row=320, column=0)
      tk.Label(sf,text="New Width",font=fos,bg="white").grid(row=290, column=0)
      a=tk.Entry(sf,width=10)
      a.grid(row=290,column=1)
      tk.Label(sf,text="New Height",font=fos,bg="white").grid(row=291, column=0)
      b=tk.Entry(sf,width=10)
      b.grid(row=291, column=1)
      tk.Button(sf,text="Enter",bg="white",font=fos, command=ccalc).grid(row=292, column=0)
    def pcrp():
      o66(283)
      o66(284)
      o66(285)
      o66(286)
      def ccalc():
        pclear()
        global img,imge
        r=eval(rp.get())
        v=eval(lp.get())
        u=eval(up.get())
        lo=eval(lop.get())
        imge=imge.crop((v,u,r,lo))
        imge.thumbnail((550,550))
        photo=ImageTk.PhotoImage(imge)
        phdisp=tk.Label(sf,image=photo)
        phdisp.image=photo
        phdisp.grid(row=320, column=0)
      tk.Label(sf,text="Right coordinate",font=fos,bg="white").grid(row=283, column=0)
      rp=tk.Entry(sf, width=10)
      rp.grid(row=283, column=1)
      tk.Label(sf,text="Left coordinate",font=fos,bg="white").grid(row=284, column=0)
      lp=tk.Entry(sf, width=10)
      lp.grid(row=284, column=1)
      tk.Label(sf,text="Upper coordinate",font=fos,bg="white").grid(row=285, column=0)
      up=tk.Entry(sf, width=10)
      up.grid(row=285, column=1)
      tk.Label(sf,text="Lower coordinate",font=fos,bg="white").grid(row=286, column=0)
      lop=tk.Entry(sf, width=10)
      lop.grid(row=286, column=1)
      tk.Button(sf,text="Enter",font=fos,bg="white", command=ccalc).grid(row=287, column=0)
    def phinfo():
      o66(277)
      o66(278)
      o66(279)
      o66(280)
      fp=str(x.get("1.0",tk.END)).strip()
      pclear()
      global img
      if fp=="":
        img=Image.open("/storage/emulated/0/Android/media/com.whatsapp/whatsapp/Media/WhatsApp Images/IMG-20250111-WA0000.jpg")
      else :
        img=Image.open(fp)
      global imge
      imge=img.copy()
      
      tk.Label(sf,text="Details are:-",font=fos,bg="white").grid(row=276, column=0)
      tk.Label(sf,text="Height",font=fos,bg="white").grid(row=277, column=0)
      tk.Label(sf,text=img.size[1],font=fos,bg="white").grid(row=277, column=1)
      tk.Label(sf,text="Width",font=fos,bg="white").grid(row=278, column=0)
      tk.Label(sf,text=img.size[0],font=fos,bg="white").grid(row=278, column=1)
      tk.Label(sf,text="Format",font=fos,bg="white").grid(row=279, column=0)
      tk.Label(sf,text=img.format,font=fos,bg="white").grid(row=279,column=1)
      tk.Label(sf,text="Mode",font=fos,bg="white").grid(row=280, column=0)
      tk.Label(sf,text=img.mode,font=fos,bg="white").grid(row=280, column=1)
       
      imge.thumbnail((550,550))
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=320, column=0)
      img.thumbnail((img.size[0],img.size[1]))
    tk.Label(sf,text="File path",font=fos,bg="white").grid(row=273, column=0)
    x=tk.Text(sf,width=35, height=6)
    x.grid(row=274, column=0)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=phinfo).grid(row=275, column=0)
    tk.Button(sf,text="Crop",font=fos,bg="Red", command=pcrp).grid(row=282, column=0)
    tk.Button(sf,text="Resize",font=fos,bg="red", command=rsp).grid(row=289, column=0)
    tk.Button(sf,text="Rotate",font=fos,bg="red",command=rop).grid(row=293, column=0)
    tk.Button(sf,text="Highlight edge",font=fos,bg="red", command=phe).grid(row=297, column=0)
    tk.Button(sf,text="3D effect",font=fos,bg="red", command=p3d).grid(row=298, column=0)
    tk.Button(sf,text="Detect edge",font=fos,bg="red", command=pde).grid(row=299, column=0)
    tk.Button(sf,text="Reset",font=fos,bg="red", command=pres).grid(row=301, column=0)
    tk.Button(sf,text="Save",font=fos,bg="red", command=psve).grid(row=303, column=0)
  def creation():
    o66(265)
    o66(266)
    o66(269)
    def cre():
      hei=eval(h.get())
      wed=eval(w.get())
      col=str(coli.get())
      doc=dict(Red=(255,0,0),Green=(0,255,0),Blue=(0,0,255),White=(255,255,255),Black=(0,0,0), Yellow=(255,255,0),Magneta=(255,0,255),Cyan=(0,255,255),Pink=(255,192,203),Orange=(255,165,0), Purple=(128,0,128))
      imge=Image.new("RGB",(wed,hei),doc[col.title()])
      pc=ImageTk.PhotoImage(Image.new("RGB",(550,550),(255,255,255)))
      phdsp=tk.Label(sf,image=pc)
      phdsp.image=pc
      phdsp.grid(row=271, column=0)
      photo=ImageTk.PhotoImage(imge)
      phdisp=tk.Label(sf,image=photo)
      phdisp.image=photo
      phdisp.grid(row=271, column=0)
    tk.Label(sf,text="Height",font=fos,bg="white").grid(row=265, column=0)
    h=tk.Entry(sf, width=10)
    h.grid(row=265, column=1)
    tk.Label(sf,text="Width",font=fos,bg="white").grid(row=266, column=0)
    w=tk.Entry(sf,width=10)
    w.grid(row=266, column=1)
    tk.Label(sf,text="Colour",font=fos,bg="white").grid(row=269, column=0)
    coli=tk.Entry(sf, width=10)
    coli.grid(row=269, column=1)
    tk.Button(sf,text="Enter",font=fos,bg="white", command=cre).grid(row=270, column=0)
  tk.Button(sf,text="Create",font=fos,bg="black",fg="white", command=creation).grid(row=264, column=0)
  tk.Button(sf,text="Modify",font=fos,bg="black",fg="white", command=modf).grid(row=272, column=0)
  
  

   
  
  
##################
bt1=tk.Button(sf,text="Add", command=add,bg="white")
bt1.grid(column=0,row=3)
bt2=tk.Button(sf,text="Subtract",command=sub,bg="white").grid(column=0,row=9)
bt3=tk.Button(sf,text="Multiply",command=mul,bg="white").grid(column=0,row=15)
bt4=tk.Button(sf,text="Divide",command=div,bg="white").grid(column=0,row=21)
bt5=tk.Button(sf,text="Square Root",command=sqr,bg="white").grid(column=0,row=27)
bt6=tk.Button(sf,text="Factorial",command=fact,bg="white").grid(column=0,row=32)
bt7=tk.Button(sf,text="Power",command=pow,bg="white").grid(column=0,row=37)
bt8=tk.Button(sf,text="Trigonometry",command=trig,bg="white").grid(column=0,row=43)
bt9=tk.Button(sf,text="Area", command=area,bg="white").grid(column=0,row=75)
bt10=tk.Button(sf,text="Inverse Trigonometric Functions",command=itrig,bg="white").grid(row=125,column=0)
bt11=tk.Button(sf,text="Log", command=Log,bg="white").grid(row=156, column=0)
bt12=tk.Button(sf,text="Ln", command=ln,bg="white").grid(row=162, column=0)
bt13=tk.Button(sf,text="Calculus",font=fos,bg="white", command=calculus).grid(row=166, column=0)
bt14=tk.Button(sf,text="Matrix",bg="white",font=fos, command=mat).grid(row=181, column=0)
bt15=tk.Button(sf,text="Polynomial", command=eq,bg="white").grid(row=247,column=0)
bt16=tk.Button(sf,text="Language Translator", command=langt,bg="white").grid(row=252, column=0)
bt17=tk.Button(sf,text="Graph", command=graphe,bg="white").grid(row=257, column=0)
bt18=tk.Button(sf,text="Photo editor", command=phoed,bg="white").grid(row=263, column=0)
#################
for t in range(100):
  tk.Label(sf).grid(row=499+t, column=0)
  tk.Label(sf).grid(row=0, column=t+599)
sf.update_idletasks()
window.update_idletasks()
c.configure(scrollregion=c.bbox("all"))
window.mainloop()